In [1]:
import numpy as np
import pandas as pd

In [2]:
date=pd.read_csv('/content/orders.csv')
time=pd.read_csv('/content/messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [7]:
date['date']=pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# Extract year

In [9]:
date['date_year']=date['date'].dt.year

In [10]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

# Extract Month

In [11]:
date['date_month']=date['date'].dt.month

In [12]:
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [17]:
date['date_month_name']=date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,1,December
1,2018-08-15,3646,14,157,2018,2,August
2,2018-10-23,1859,25,1,2018,1,October
3,2019-08-17,7292,25,1,2019,5,August
4,2019-01-06,4344,25,3,2019,6,January

In [18]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,1,December,10
1,2018-08-15,3646,14,157,2018,2,August,15
2,2018-10-23,1859,25,1,2018,1,October,23
3,2019-08-17,7292,25,1,2019,5,August,17
4,2019-01-06,4344,25,3,2019,6,January,6

In [19]:
date['date_dayofweek']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dayofweek
0,2019-12-10,5628,25,3,2019,1,December,10,1
1,2018-08-15,3646,14,157,2018,2,August,15,2
2,2018-10-23,1859,25,1,2018,1,October,23,1
3,2019-08-17,7292,25,1,2019,5,August,17,5
4,2019-01-06,4344,25,3,2019,6,January,6,6

In [20]:
date['date_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dayofweek,date_name
0,2019-12-10,5628,25,3,2019,1,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,2,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,1,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,5,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,6,January,6,6,Sunday

In [21]:
date['date_is_weekend']=np.where(date['date_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dayofweek,date_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,1,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,2,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,1,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,5,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,6,January,6,6,Sunday,1

In [23]:
date['date_week']=date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dayofweek,date_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,1,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,2,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,1,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,5,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,6,January,6,6,Sunday,1,1

In [24]:
date['date_quarter']=date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dayofweek,date_name,date_is_weekend,date_week,date_quarter
0,2019-12-10,5628,25,3,2019,1,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,2,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,1,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,5,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,6,January,6,6,Sunday,1,1,1

In [25]:
date['date_semester']=np.where(date['date_quarter'].isin([1,2]),1,2)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dayofweek,date_name,date_is_weekend,date_week,date_quarter,date_semester
0,2019-12-10,5628,25,3,2019,1,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,2,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,1,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,5,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,6,January,6,6,Sunday,1,1,1,1

In [26]:
import datetime

today=datetime.datetime.today()

today

datetime.datetime(2024, 10, 15, 19, 36, 13, 811594)

In [28]:
today-date['date']

0     0 days
1     0 days
2     0 days
3     0 days
4     0 days
       ...
995   0 days
996   0 days
997   0 days
998   0 days
999   0 days
Name: date, Length: 1000, dtype: timedelta64[ns]

In [29]:
(today-date['date']).dt.days

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: date, Length: 1000, dtype: int64

In [34]:

# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'D'),0)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: date, Length: 1000, dtype: float64

In [35]:
time['date']=pd.to_datetime(time['date'])
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [36]:
time['hour']=time['date'].dt.hour
time['minute']=time['date'].dt.minute
time['second']=time['date'].dt.second

time.head()

,date,msg,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [37]:
time['time']=time['date'].dt.time

In [38]:
time.head()

,date,msg,hour,minute,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [39]:
today - time['date']

0     2185 days 23:10:00
1     1568 days 00:20:00
2     2122 days 23:39:00
3     1722 days 23:29:00
4     1897 days 00:49:00
             ...
995   2396 days 23:10:00
996   1777 days 00:46:00
997   2394 days 00:23:00
998   2445 days 00:26:00
999   1943 days 00:35:00
Name: date, Length: 1000, dtype: timedelta64[ns]

In [40]:
np.round((today - time['date']) / np.timedelta64(1, 'm'),0)

0      3147790.0
1      2257940.0
2      3057099.0
3      2481089.0
4      2731729.0
         ...
995    3451630.0
996    2558926.0
997    3447383.0
998    3520826.0
999    2797955.0
Name: date, Length: 1000, dtype: float64

In [41]:
np.round((today - time['date']) / np.timedelta64(1, 'h'),0)

0      52463.0
1      37632.0
2      50952.0
3      41351.0
4      45529.0
        ...
995    57527.0
996    42649.0
997    57456.0
998    58680.0
999    46633.0
Name: date, Length: 1000, dtype: float64

In [42]:
np.round((today - time['date']) / np.timedelta64(1, 's'),0)

0      188867400.0
1      135476400.0
2      183425940.0
3      148865340.0
4      163903740.0
          ...
995    207097800.0
996    153535560.0
997    206842980.0
998    211249560.0
999    167877300.0
Name: date, Length: 1000, dtype: float64